apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: db
    tier: database
data:
  MYSQL_USER: myuser
  MYSQL_PASSWORD: "password"
  MYSQL_DATABASE: laravelio
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"