---
# Service for exposing MySQL
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db
    tier: database
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - targetPort: 3306 # port that containers are listening on
      port: 3306 # port number exposed internally in the cluster
      