apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: laravelio-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravelio
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 80
